# Generated by Django 4.1.3 on 2023-01-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='doctor_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Doctor Type'),
        ),
    ]
