# Generated by Django 4.1.3 on 2023-01-13 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usercomplaints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomplaints',
            name='user',
        ),
    ]
