# Generated by Django 4.1.3 on 2023-01-13 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_remove_usercomplaints_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomplaints',
            name='user',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
