# Generated by Django 4.1.3 on 2023-01-13 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usercomplaints_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomplaints',
            name='user',
        ),
        migrations.AddField(
            model_name='usercomplaints',
            name='profile',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
