# Generated by Django 4.1.3 on 2023-01-13 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_usercomplaints_user_usercomplaints_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomplaints',
            name='profile',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
