# Generated by Django 4.1.3 on 2023-01-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_usercomplaints_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomplaints',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
