# Generated by Django 4.1.3 on 2023-01-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_usercomplaints_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomplaints',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
