# Generated by Django 4.1.3 on 2023-01-13 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_usercomplaints_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomplaints',
            old_name='date_time',
            new_name='created_at',
        ),
    ]
