# Generated by Django 4.1.3 on 2023-01-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_date_time_usercomplaints_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomplaints',
            name='open_close',
            field=models.BooleanField(default=False),
        ),
    ]
